Metadata-Version: 2.3
Name: fastapi_exception
Version: 1.3.8
Summary: FastAPI Event
Project-URL: Homepage, https://github.com/megatron-global/fastapi-exception
Project-URL: Bug Tracker, https://github.com/megatron-global/fastapi-exception/issues
Author-email: Dzung Nguyen <dung@megatron-solutions.com>
License-File: LICENSE
Classifier: License :: OSI Approved :: MIT License
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python :: 3
Requires-Python: >=3.11
Requires-Dist: fastapi-global-variable>=0.0.4
Requires-Dist: pydantic>=2.6.0
Requires-Dist: python-keycloak>=2.14.0
Description-Content-Type: text/markdown

# FastAPI Exception

### Setup python environment

```shell
python3 -m venv venv
```

### Active the python environemt

```shell
. venv/bin/activate
```

### Install requirements

```shell
pip install -r requirements.txt
```

## How to use

```python
# Init FastAPI

# config/exception.py
from config.i18n import i18n_service
from fastapi_exception import FastApiException

FastApiException.init()
FastApiException.init(translator_service=i18n_service) # pass translator_service if we integrate with i18n
```
