def exception_factory(exception, message):
    return exception(message)
