class AutomizorVaultError(RuntimeError):
    """Exception raised for errors encountered while interacting with the Vault."""
